export const competitionChallenges=[
  {id:'daily-board',tag:'DAILY RULE VARIANT',name:'The daily mutation.',description:'A shared UTC-day board with a new size, winning line or gravity. Play it free, then share your setup.',action:'Prepare today’s board',visual:'▦'},
  {id:'connect4-sprint',tag:'FAST & TACTICAL',name:'Four in a hurry.',description:'Play Connect Four against the free Tactician. Find the winning line before your rival does.',action:'Prepare the sprint',visual:'●'},
  {id:'nim-duel',tag:'SMALL GAME. BIG TRAP.',name:'Take the last stone.',description:'Three heaps. One final move. Challenge the free opponent in Nim, then bring your own agent.',action:'Prepare a Nim duel',visual:'•••'},
  {id:'oracle-duel',tag:'BEAT THE BASELINE',name:'Hold the draw.',description:'Face the qualified tic-tac-toe Oracle. Can you stay undefeated against perfect play?',action:'Prepare the Oracle duel',visual:'×○'},
  {id:'mirror-match',tag:'FOUR GAMES. BOTH SEATS.',name:'The mirror match.',description:'Compare two free contenders in a seat-swapped Connect Four series. Keep the whole evaluation.',action:'Prepare a free series',visual:'⇄'},
] as const;
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function challengeCards(embedded=false){return `<div class="challenge-grid">${competitionChallenges.map(c=>`<article class="challenge-card"><div class="challenge-symbol" aria-hidden="true">${escape(c.visual)}</div><p class="eyebrow">${c.tag}</p><h3>${c.name}</h3><p>${c.description}</p>${embedded?`<button data-challenge="${c.id}">${c.action} ↗</button>`:`<a href="/#challenge=${c.id}">${c.action} ↗</a>`}<span class="challenge-footnote">Free setup · you choose when to play</span></article>`).join('')}<article class="challenge-card"><div class="challenge-symbol" aria-hidden="true">◇</div><p class="eyebrow">CREATOR COMPETITION</p><h3>Make the rules.</h3><p>Build a connect-in-a-row arena, export the rules, and challenge a friend or agent to adapt.</p><a href="${embedded?'#forge':'/#forge'}">Open the Forge ↗</a><span class="challenge-footnote">Custom boards · portable rules</span></article><article class="challenge-card"><div class="challenge-symbol" aria-hidden="true">⚔</div><p class="eyebrow">FRIEND VS FRIEND</p><h3>Settle it on the board.</h3><p>Invite a friend into a private peer-to-peer duel. Choose your agents and keep the replay.</p><a href="${embedded?'#duel':'/#duel'}">Create a duel ↗</a><span class="challenge-footnote">Live peer connection · your own contenders</span></article><article class="challenge-card"><div class="challenge-symbol" aria-hidden="true">▶</div><p class="eyebrow">WATCH & LEARN</p><h3>Read the rival.</h3><p>Inspect all 24 completed circuit games. Seek through the moves and spot the turning point.</p><a href="/circuits/launch-ttt-v1">Explore public replays ↗</a><span class="challenge-footnote">Published circuit · retained evidence</span></article></div>`;}
