import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readdir, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { RULES, createGame, replayStepper, validateRules, legalMoves, type Rules } from "../src/runtime";
import { baselinePolicy, WorkBudget } from "../src/self-improvement";
import { tacticalChoices, gradeTactic, fixedOpponentMove, strengthSuite } from "../src/strength";
import { measureStrength } from "../scripts/measure-strength";

const budget = () => new WorkBudget(500000, 30000);
const custom = validateRules({ kind: "custom", name: "Fixture three", rows: 3, cols: 3, connect: 3, gravity: false });
function position(rules: Rules, moves: string[]) {
  const step = replayStepper(rules);
  return moves.reduce((_s, move) => step(move), createGame(rules));
}

// Expected moves are hand-labeled from replay histories, not generated by the grader.
const fixtures = [
  { name: "ttt white win", rules: RULES.tictactoe, moves: ["0", "3", "1", "4"], seat: 0, kind: "win", correct: "2", wrong: "8" },
  { name: "ttt black win", rules: RULES.tictactoe, moves: ["0", "3", "1", "4", "8"], seat: 1, kind: "win", correct: "5", wrong: "6" },
  { name: "ttt black defense", rules: RULES.tictactoe, moves: ["0", "4", "1"], seat: 1, kind: "defense", correct: "2", wrong: "8" },
  { name: "ttt white defense", rules: RULES.tictactoe, moves: ["4", "0", "8", "1"], seat: 0, kind: "defense", correct: "2", wrong: "6" },
  { name: "connect white win", rules: RULES.connect4, moves: ["0", "6", "1", "6", "2", "5"], seat: 0, kind: "win", correct: "3", wrong: "4" },
  { name: "connect black win", rules: RULES.connect4, moves: ["6", "0", "6", "1", "5", "2", "4"], seat: 1, kind: "win", correct: "3", wrong: "5" },
  { name: "connect black defense", rules: RULES.connect4, moves: ["0", "6", "1", "6", "2"], seat: 1, kind: "defense", correct: "3", wrong: "5" },
  { name: "custom white win", rules: custom, moves: ["0", "3", "1", "4"], seat: 0, kind: "win", correct: "2", wrong: "8" },
  { name: "custom black defense", rules: custom, moves: ["0", "4", "1"], seat: 1, kind: "defense", correct: "2", wrong: "8" },
];

test("hand-labeled tactics distinguish deliberately wrong moves across three short-game recipes and both seats", () => {
  for (const f of fixtures) {
    const state = position(f.rules, f.moves), before = JSON.stringify(state);
    assert.equal(state.turn, f.seat, f.name);
    const tactics = tacticalChoices(state, budget());
    const good = gradeTactic(tactics, f.correct), bad = gradeTactic(tactics, f.wrong);
    assert.equal(good.legal, true, f.name);
    assert.equal(bad.legal, true, f.name);
    assert.equal(good.missedWin || good.avoidableLoss, false, f.name);
    assert.equal(f.kind === "win" ? bad.missedWin : bad.avoidableLoss, true, f.name);
    assert.equal(fixedOpponentMove(state, "immediate-tactics-v1", 7, budget()), f.correct, f.name);
    assert.equal(JSON.stringify(state), before, f.name);
  }
});

test("chess fool's mate is a win opportunity and an illegal response never counts as a tactical pass", () => {
  const state = position(RULES.chess, ["f2f3", "e7e5", "g2g4"]);
  const tactics = tacticalChoices(state, budget());
  assert.ok(tactics.wins.includes("d8h4"));
  assert.equal(gradeTactic(tactics, "d8h4").missedWin, false);
  assert.equal(gradeTactic(tactics, "b8c6").missedWin, true);
  assert.deepEqual(gradeTactic(tactics, "invalid"), { legal: false, assessed: false, winOpportunity: false, missedWin: false, defenseOpportunity: false, avoidableLoss: false });
});

test("a rule-complete draw is safe and never an avoidable loss", () => {
  const draw = position(RULES.tictactoe, ["0", "4", "8", "2", "6", "3", "5", "7"]);
  const tactics = tacticalChoices(draw, budget());
  assert.deepEqual(tactics.safe, ["1"]);
  assert.deepEqual(gradeTactic(tactics, "1"), { legal: true, assessed: true, winOpportunity: false, missedWin: false, defenseOpportunity: false, avoidableLoss: false });
});

test("frozen opponents are legal for checkers and reproducible for matching seeds", () => {
  const state = createGame(RULES.checkers);
  for (const opponent of ["seeded-random-v1", "immediate-tactics-v1"] as const) {
    const chosen = fixedOpponentMove(state, opponent, 4, budget());
    assert.ok(legalMoves(state).includes(chosen));
    assert.equal(fixedOpponentMove(state, opponent, 4, budget()), chosen);
  }
  assert.throws(() => fixedOpponentMove(state, "unknown" as any, 4, budget()), /Unknown/);
  assert.throws(() => tacticalChoices(state, new WorkBudget(1)), /budget/);
  const aborted = new AbortController(); aborted.abort();
  assert.throws(() => tacticalChoices(state, new WorkBudget(100, 1000, aborted.signal)));
});

test("strength report is deterministic, seat-separated, non-promoting, and leaves the policy unchanged", async () => {
  const policy = await baselinePolicy(RULES.tictactoe), before = JSON.stringify(policy);
  const a = await strengthSuite(policy, [1, 2, 3, 4], 9, budget());
  assert.deepEqual(a, await strengthSuite(policy, [1, 2, 3, 4], 9, budget()));
  assert.equal(JSON.stringify(policy), before);
  assert.equal(a.games.length, 16);
  assert.equal(a.groups.length, 4);
  assert.equal(a.promotion, "not-authorized");
  assert.ok(a.groups.every(g => g.completed === 4 && g.illegalMoves === 0));
  for (const game of a.games) assert.equal(position(policy.rules, game.moves).winner, game.winner);
  await assert.rejects(strengthSuite(policy, [1, 1], 9, budget()), /seeds/);
  await assert.rejects(strengthSuite(policy, [1], 401, budget()), /cap/);
  await assert.rejects(strengthSuite(policy, [1], 399, budget()), /cap/);
  assert.ok((await strengthSuite(policy, [1], 398, budget())).games.every(g => g.complete));
});

test("capped outcomes are never counted as draws or scored; no-opportunity rates are null", async () => {
  const report = await strengthSuite(await baselinePolicy(RULES.tictactoe), [1], 1, budget());
  assert.ok(report.groups.every(g => g.capped === 1 && g.completed === 0 && g.score === null));
  assert.ok(report.groups.every(g => g.missedWinRate === null && g.avoidableLossRate === null));
  const edge = createGame(RULES.tictactoe); edge.moves = Array(398).fill("fixture-boundary");
  assert.equal(tacticalChoices(edge, budget()).assessed, false);
  assert.throws(() => fixedOpponentMove(edge, "immediate-tactics-v1", 0, budget()), /boundary/);
});

test("CLI preserves source-bound plan and report; exhausted budget records failure without success", async () => {
  const dir = await mkdtemp(join(tmpdir(), "bw-strength-"));
  try {
    const result = await measureStrength(["--pairs", "1", "--max-plies", "9", "--output", dir]);
    const report = JSON.parse(await readFile(join(result.output, "report.json"), "utf8"));
    assert.equal(result.digest, report.digest);
    const plan = JSON.parse(await readFile(join(result.output, "plan.json"), "utf8"));
    assert.ok(plan.source.strength && plan.source.outcome);
    assert.deepEqual(plan.budget, { nodes: 500000, seconds: 120 });
    await assert.rejects(measureStrength(["--pairs", "1", "--nodes", "1", "--output", dir]), /budget/);
    const failed = (await readdir(dir)).find(name => join(dir, name) !== result.output)!;
    assert.equal(JSON.parse(await readFile(join(dir, failed, "failure.json"), "utf8")).promotion, "not-authorized");
    await assert.rejects(readFile(join(dir, failed, "report.json")));
    await assert.rejects(measureStrength(["--pairs", "1", "--pairs", "2"]), /duplicate/);
    await assert.rejects(measureStrength(["--max-plies", "399"]), /cap/);
    for (const [option, value] of [["--nodes", "NaN"], ["--nodes", "-1"], ["--nodes", "2000001"], ["--seconds", "Infinity"], ["--seconds", "-1"], ["--seconds", "301"]]) {
      await assert.rejects(measureStrength([option, value]), /budget/);
    }
  } finally { await rm(dir, { recursive: true, force: true }); }
});
