import { build } from "esbuild";
import { createHash } from "node:crypto";
import { mkdir, writeFile, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const chessLicense = (await readFile(path.join(root, "node_modules/chess.js/LICENSE"), "utf8")).replaceAll("\r\n", "\n");
const projectLicense = (await readFile(path.join(root, "../LICENSE"), "utf8")).replaceAll("\r\n", "\n");
const result = await build({
  absWorkingDir: root, entryPoints: ["src/referee.ts"], bundle: true, write: false,
  format: "esm", platform: "neutral", mainFields: ["module", "main"], target: "es2022", legalComments: "inline",
  charset: "utf8", sourcemap: false,
  footer: { js: `/*! BuilderWars\n${projectLicense.replaceAll("*/", "* /")}\n*/\n/*! chess.js 1.4.0\n${chessLicense.replaceAll("*/", "* /")}\n*/` },
});
if (result.outputFiles.length !== 1) throw Error("Referee must be a self-contained module.");
const bytes = result.outputFiles[0].contents;
const digest = createHash("sha256").update(bytes).digest("hex");
const integrity = `sha256-${createHash("sha256").update(bytes).digest("base64")}`;
const file = `referee/${digest}.mjs`;
await mkdir(path.join(root, "public/referee"), { recursive: true });
// Immutable filenames: never replace another engine's snapshot.
const target = path.join(root, "public", file);
try {
  if (!Buffer.from(await readFile(target)).equals(Buffer.from(bytes))) throw Error("Snapshot collision.");
} catch (error) {
  if (error.code !== "ENOENT") throw error;
  await writeFile(target, bytes, { flag: "wx" });
}
const manifest = { digest, integrity, file, verifier: `referee/verify-${digest}.mjs` };
await writeFile(path.join(root, "src/referee-manifest.ts"), `// Generated by build-referee.mjs; do not edit.\nexport default ${JSON.stringify(manifest)} as const;\n`);
const cli = `#!/usr/bin/env node
// BuilderWars portable board verifier. Keep this file alongside your proof.
// Verifies rule replay only, not model identity, autonomous execution or billing.
// Runtime: Node.js 22+. No packages or network required. Trusted code is embedded,
// never loaded from a match file. Referee source: https://github.com/nymrel/builderwars
import { readFile, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const engine = ${JSON.stringify(digest)};
const payload = ${JSON.stringify(Buffer.from(bytes).toString("base64"))};
try {
  if (process.argv.length !== 3) throw Error('Usage: node verify-<engine>.mjs match.jsonl');
  const source = Buffer.from(payload, 'base64');
  if (createHash('sha256').update(source).digest('hex') !== engine) throw Error('Verifier engine integrity failure.');
  if ((await stat(process.argv[2])).size > 1500000) throw Error('Proof exceeds size limit.');
  const text = new TextDecoder('utf-8', { fatal: true }).decode(await readFile(process.argv[2]));
  const referee = await import('data:text/javascript;base64,' + payload);
  const verified = await referee.verifyProof(text, engine);
  console.log(JSON.stringify({ verified: true, protocol: referee.PROOF_PROTOCOL, engine,
    game: verified.record.rules.name, plies: verified.record.events.length,
    complete: verified.state.over, winner: verified.state.over ? verified.state.winner : null,
    reason: verified.record.status, origin_declaration: verified.origin,
    model_attested: false, execution_attested: false, billing_attested: false }));
} catch (error) {
  console.error(JSON.stringify({ verified: false, error: error instanceof Error ? error.message : 'Verification failed.' }));
  process.exitCode = 1;
}
`;
await writeFile(path.join(root, "public", manifest.verifier), cli);
console.log(`Referee ${digest} (${bytes.length} bytes); portable verifier generated.`);
